[build]
  publish = "."
  command = ""

# Optional: pretty URLs (so /hearing works)
[[redirects]]
  from = "/hearing"
  to   = "/hearing.html"
  status = 200

[[redirects]]
  from = "/deaf-youtube"
  to   = "/deaf-youtube.html"
  status = 200


# Root fallback for invalid paths
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
