[build]
  publish = "."
  command = ""

# pretty URLs chahiye to:
[[redirects]]
  from = "/hearing"
  to   = "/hearing.html"
  status = 200

[[redirects]]
  from = "/deaf-youtube"
  to   = "/deaf-youtube.html"
  status = 200
